### PR TITLE
Added anaconda_toggle_linting command

### PR DESCRIPTION
**Pull request by vindolin**

### CODE REVIEW

**Comment by DamnWidget** [comment]
I am confused, why are you adding a feature that already exists?

https://github.com/DamnWidget/anaconda/blob/master/Default.sublime-commands#L3-L8
https://github.com/DamnWidget/anaconda/blob/master/commands/disable_linting.py
https://github.com/DamnWidget/anaconda/blob/master/commands/enable_linting.py

**Comment by vindolin** [comment]
I'm working on a huge legacy project where I have to toggle the linting very often and I was used to the sublime toggle_comment behavior.
Also this only needs one keyboard shortcut.
So I implemented this mainly for my own sanity and thought that could be of use to someone.

**Comment by DamnWidget** [comment]
I think is better if you just create a plugin in your userspace (a directory in your `Packages/User`) with the command file and the key bindings that you want for this, it will work and is just what you want.

**Comment by vindolin** [comment]
Ok, no problem.

**Pull request closed without merging**
