### PR TITLE
Fixes issue in which the wrong line is highlighted when validating imports. Resolves #337.

### LINKED ISSUE #337: Import validator not working
Import validator does not appear to be working using the current code from git.

 "validate_imports": true is set in User/Anaconda.sublime-settings, but entering an obviously bogus import statement shows no error or other indication. Other Anaconda functions (linting, go to definition, etc.) all seem to be working fine.

### PR DESCRIPTION
**Pull request by Effenberg0x0**

### CODE REVIEW

**Comment by DamnWidget** [comment]
Hi @Effenberg0x0 
This PR must wait until I release 2.0.0 (hopefully this week), I will check it then.

**Comment by Effenberg0x0** [comment]
Awesome, I'm looking forward to v. 2.0.
Thanks.

**Comment by DamnWidget** [comment]
Hi, until all the bug reports related with 2.0.0 are fixed/resolved this PR is gonna have to wait, I hope you don't mind.

**Comment by Effenberg0x0** [comment]
Sure, no problem. I'm actually investigating other bugs and hopefully will have other pull requests for you soon if I succeed. No rush.

**Pull request merged**
