### PR TITLE
fix: fix anaconda to work with Python 3.10

### PR DESCRIPTION
**Pull request by DamnWidget**
# Abstract

This PR fixes several issues that had been stacking up in anaconda during the years. The Python language has been evolving pretty fast in the lat years, it is currently in the top of all language lists and support for older versions and compatibility is being dropped everywhere pretty fast.

Anaconda has been in low maintenance mode for several years now, this made users environments to break now and then depending on the Python version they were working with. This PR solves this problem for anyone using a modern enough version of Python,

**NOTE**: Please, checkout this branch and give it a test 
**SOLVES**: #921 
**SUPER IMPORTANT**: This branch will work with Sublime Text 4 build 4107 or higher **only**

## What has been fixed and tested

I fixed and tested myself the following features that were broken in Python 3.10

* Autocompletion 
* Goto Definition
* Goto Assignment
* Show Signatures
* Hover Documentation
* Show Documentation
* Python 3.10 features linting 

I tested all of it in an Artix Linux box, I didn't test it on Windows or MacOS (and I will not)

## What was not tested?

* Vagrant support
* Docker support
* Remote interpreter support of any kind
* Docstrings Linting

## Library Updates

* Update Parso to latest version
* Update Jedi to latest version
* Update PyFlakes to latest version
* Update PyCodestyle to latest version
* Update McCabe to latest version
* Added support for Pylint >= 2.5.0

## Additional Changes

* Dropped support for Python < 3.6

## Things in Danger

When I created this plugin, almost a decade ago, there was no **asyncio** or language servers so I created my own AsyncIO loop and my own language server, it worked fine, and made anaconda the most responsive plugin in ST ecosystem for long time, but those days of glory are gone, the server side of anaconda uses **asynchat** (the oldest dumb brother of asyncio) that is deprecated as shit, so there is a real danger of the plugin being completely broken and with not avail in future Python releases.

I will try to "modernize" some stuff, but I make no promises

### CODE REVIEW

**Comment by aleksbykov** [comment]
I got next issue on ubuntu 20.04:
```
reloading python 3.3 plugin Anaconda.anaconda
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/abykov/.config/sublime-text/Packages/Anaconda/anaconda.py", line 21, in <module>
    from .commands import *   # noqa
  File "/home/abykov/.config/sublime-text/Packages/Anaconda/commands/__init__.py", line 7, in <module>
    from .get_lines import AnacondaGetLines
  File "/home/abykov/.config/sublime-text/Packages/Anaconda/commands/get_lines.py", line 11, in <module>
    from ..anaconda_lib.linting.sublime import ANACONDA
  File "/home/abykov/.config/sublime-text/Packages/Anaconda/anaconda_lib/linting/sublime.py", line 12, in <module>
    from . import pycodestyle as pep8
  File "/home/abykov/.config/sublime-text/Packages/Anaconda/anaconda_lib/linting/pycodestyle.py", line 455
    yield found, f"{code} whitespace before '{char}'"
                                                    ^
```

**Comment by DamnWidget** [comment]
> 

Hi @aleksbykov 

As it is in the notes, python support for versions prior to 3.6 has been dropped, this includes the Sublime Text Python interpreter itself, afaik, SublimeText4 build 4126 comes with a Python 3.8 embedded interpreter, it was introduced in build 4107

I can see that ST is loading the plugin from `/opt/sublime_text/Lib/python33/sublime_plugin.py` not sure why it is in a `python33` directory, try to completely remove it and place it in some other location, like, your User packages directory

**Comment by aleksbykov** [comment]
@DamnWidget ,
i totally remove the sublime and reinstall it again. 
after installation i have both 
/opt/sublime_text/Lib/python33/
/opt/sublime_text/Lib/python38/

Could not find why it use the python33 for load anaconda plugin

**Comment by DamnWidget** [comment]
> @DamnWidget , i totally remove the sublime and reinstall it again. after installation i have both /opt/sublime_text/Lib/python33/ /opt/sublime_text/Lib/python38/
> 
> Could not find why it use the python33 for load anaconda plugin

Look like I need to add a `.python-version` file to the root of the plugin stating the version that is preferred, looks like the left the Python33 support in there for legacy plugins, will take a look after work, let me know if you were able to run the thing

**Comment by aleksbykov** [comment]
I remove python33, but several plugins and anaconda also are not loaded
after backed it , the same error appeared. Looks you are right , need somehow set version explicitly

**Comment by DamnWidget** [comment]
> I remove python33, but several plugins and anaconda also are not loaded after backed it , the same error appeared. Looks you are right , need somehow set version explicitly

I already added the file, give it a try

**Comment by DamnWidget** [comment]
How are we looking in Windows and Mac @MattDMo? Did you have any chance to test it?

**Pull request merged**
