### PR TITLE
add option to run mypy with fast_parser

### PR DESCRIPTION
**Pull request by akdor1154**
MyPy needs to be run with `--fast-parser` to understand `async` function definitions. This PR adds an option in the sublime plugin config to run it as such.

To test, see
```py3
async def f(i: int) -> str:
  return i
```
This currently gives a parse error, but lints correctly with mypy when the added option is set.

---

I tried to write a unit test but I couldn't get the test suite to run. Am I just meant to run `nosetests3` in the `anaconda` directory? This gives
```
======================================================================
ERROR: Failure: ImportError (No module named 'jedi.parser.utils')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/jarrad/src/web/anaconda/anaconda_lib/jedi/api/__init__.py", line 20, in <module>
    from jedi.parser.utils import save_parser
ImportError: No module named 'jedi.parser.utils'
```

### CODE REVIEW

**Comment by DamnWidget** [comment]
Thanks for the PR, I will include it in the next release. To run the tests run `nosetests3 test` in the anaconda directory.

**Comment by akdor1154** [comment]
thanks for the hint; tests added. Had to muck with the travis config a bit as MyPy cannot be run on Python < 3.2. Hope that's ok.

**Comment by DamnWidget** [comment]
I will release this later today @akdor1154 

I made some modifications in the top of your PR:

* Made MyPy tests to be skipped in Python 3 if MyPy is not installed
* Fix some pep8 volations
* Added support for Python 3.6

**Comment by akdor1154** [comment]
Woo. I have been using mypy nightly since putting this together and have some further changes. Bit of a mess at the moment but should be able to sort out. I'll open a new pr and continue to tweak it until the next mypy release. :)

**Pull request merged**
