### PR TITLE
Updates Jedi to 0.17

### LINKED ISSUE #742: Anaconda (Jedi) thinks staticmethod == classmethod?
## Expected Behaviour
When I write a method decorated with `staticmethod`, I expect the completion not to think that the first parameter is the class itself. That applies to `classmethod`, not `staticmethod`.

## Actual Behaviour
image

## Steps to Reproduce
```python
class A(object):

    @staticmethod
    def test(x: int):
        x
```
## ST3, Anaconda and OS versions
Latest ST3dev, latest anaconda, linux ubuntu 17.10
## ST3 Console Logs
irrelevant

## Anaconda's JsonServer Logs
```
2018-02-08 23:02:21,748: INFO    : client requests: autocomplete
2018-02-08 23:02:22,658: INFO    : client requests: lint
```

### LINKED ISSUE #781: autocomplete does not recognize local package
## Expected Behaviour
autocompletion popup window after 
```python
from my package import my_module mm
mm.
```
## Actual Behaviour
nothing happens
## Steps to Reproduce
- verified sys.environ[PYTHONPATH] includes package/module
- verified that the import works from terminal invoked ipython instance with same import syntax, running same interpreter
## ST3, Anaconda and OS versions
anaconda 2.1.29
ubuntu 14.04

## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

### LINKED ISSUE #787: How to make import autocomplete work with locally installed packages?
Hey there,
I've installed a custom package I made globally with `pip install -e mypackage` and as far as I can tell it's working correctly with scripts, also the Python repl I use can find it (Ptpython).

Unfortunately the Anaconda import autocomplete can't find it and is not populating it neither the sub packages.

Is there something I should do to make sure it can be found?  
I'm no expert in python and even less with Package distribution and so on... FWIW I can see in the python 3.7 `site-packages` folder that there is a `mypackage.egg-link` file instead of a normal folder.

I can't see any particular log in the console, I'm using ST3 3.1.1 build 3176, Anaconda 2.1.29, Windows 7 64bit.

Thank you for any suggestion!

### LINKED ISSUE #804: Why plug-Anaconda does not tell the modules when you import?
## Expected Behaviour
I expect that when importing any modules, the autocompletion will show me all the possible import options.

## Actual Behaviour
Unfortunately, auto-completion on import only starts working after I have entered 5 letters of the class I want to import.
image
image

## Steps to Reproduce
`pip install pyqt5`
`pip install pyqt5-tools`

## ST3, Anaconda and OS versions
ST3 verion 3.1.1 build 3176
Anaconda Plugin v2.1.29
Windows 10 v1809

## ST3 Console Logs
-

## Anaconda's JsonServer Logs
No logs for used python file.

P.S.
If you use the Jedi plugin, then it is all good import:
image

**The question is, is it possible to fix autocomplete in the Anaconda plugin so that it shows all possible clues, as in the screen with Jedi?**

### LINKED ISSUE #807: 'AttributeError'>: 'Definition' object has no attribute 'doc'
When I try to get the documentation of a package remotely, it does not work. Instead, I get the following information about an uncaptured exception in the terminal:

(<class 'AttributeError'>:'Definition' object has no attribute 'doc' [/home/vojavocni/anaconda3/envs/linda/lib/python3.6/asyncore.py|read|83] [/home/vojavocni/anaconda3/envs/linda/lib/python3.6/asyncore.py|handle_read_event|423] [/home/vojavocni/anaconda3/envs/linda/lib/python3.6/asynchat.py|handle_read|171] [minserver.py|found_terminator|94] [minserver.py|handle_command|112] [/home/vojavocni/ide/anaconda/anaconda_server/handlers/jedi_handler.py|run|30] [/home/vojavocni/ide/anaconda/anaconda_server/lib/anaconda_handler.py|run|48] [/home/vojavocni/ide/anaconda/anaconda_server/handlers/jedi_handler.py|doc|99] [/home/vojavocni/ide/anaconda/anaconda_server/commands/doc.py|__init__|33] [/home/vojavocni/ide/anaconda/anaconda_server/commands/base.py|__init__|14] [/home/vojavocni/ide/anaconda/anaconda_server/commands/doc.py|run|57] [/home/vojavocni/ide/anaconda/anaconda_server/commands/doc.py|_html|82])

The logs are full of these same messages, so no point in showing them. On the side note, autocompletition does work.

### LINKED ISSUE #860: Support for Python 3.6 type hints and version of jedi included in the bundle
Hello everyone!

I am using the latest version of Anaconda on SublimeText 3.2.2 on Ubuntu 18.04, installed through the package manager (I couldn't find the specific version anywhere, to be honest). I checked and it uses Jedi version 0.10.3. At the moment I am having trouble using annotations (type hinting, PEP 484) as they are not recognised (invalid syntax).

I've added the following options in the Anaconda user settings:
```
    "anaconda_linting": false,
    "mypy_py2": false,
    "python_interpreter": "python3"
```

`anaconda_linting` is set to `false` because I am using  Sublime-linting as I set up the environment a couple of years ago based on [this tutorial](https://realpython.com/setting-up-sublime-text-3-for-full-stack-python-development/).

Also in my system, Python 3 (3.6.9) is the default Python. Not sure if that translates inside Anaconda, though.

So I came to realise that the [Jedi](https://github.com/davidhalter/jedi) version in their repository is 0.17.1 and I also read [this issue](https://github.com/DamnWidget/anaconda/issues/760) and [this issue](https://github.com/DamnWidget/anaconda/issues/451). I also found [this issue](https://github.com/DamnWidget/anaconda/issues/673) and tried to follow the instructions there, but without any good results (probably my lack of knowledge).

So I have a question and a request:
* Is there any place where I can find instructions on how to update the version of the jedi package inside my anaconda installation?
* Do you have plans on updating the version of jedi included in anaconda anytime soon?

Thanks in advance.

### PR DESCRIPTION
**Pull request by scuml**
• Updates jedi to latest version.
• Auto-completion now functions within f-strings
• Validate imports (and docstring fetcher, and function parameter completion) now uses the jedi Project class - which allows for everything to just work better.  Installed site-packages are now recognized if `python_interpreter` is set.

**Please install this branch and test** as this upgrade can result in breaking changes.  Please comment below to let us know you are testing the branch, and post if things seem to be working, or if you find a breaking change.

Thanks.

Fixes #860, fixes #742, fixes #807, fixes #804, resolves #787, fixes #781

### CODE REVIEW

**Comment by DamnWidget** [comment]
Can people checkout this branch from @scuml  and give it a try? This one can break badly.

**Comment by scuml** [comment]
Closes #860, #742, #807

**Comment by scuml** [comment]
This now adds autocomplete to f-strings.

**Comment by scuml** [comment]
Marked as "Work In Progress".  Working on problem with auto-formatting where blocks of code are deleted.

**Comment by scuml** [comment]
Closes #804

**Comment by scuml** [comment]
Looking for testers (especially Windows users) to verify this branch.  

Please download branch from https://github.com/scuml/anaconda/tree/upgrade-jedi-17
Drag to Sublime Pacakages folder, replacing the Anaconda directory.
Restart Sublime.

Please comment on this pull request if you experience a problem or if the branch is working here.  Thanks.

**Comment by DamnWidget** [comment]
@scuml doesn't looks like the community is aiming for providing any kind of help on this, if we merge there will be reports within minutes after release, if you are ok with handling it we can go for it, let me know what you think.

**Comment by scuml** [comment]
Really could use a confirmation on a Windows box.  I've got a full plate this week, but how about early next week you could merge it and I'll try to deal with the fallout.

**Comment by scuml** [comment]
@DamnWidget  - if it's okay with you, let's go ahead and get this PR merged before it gets too stale.

**Comment by MichaelHarush** [comment]
> Looking for testers (especially Windows users) to verify this branch.
> 
> Please download branch from https://github.com/scuml/anaconda/tree/upgrade-jedi-17
> Drag to Sublime Pacakages folder, replacing the Anaconda directory.
> Restart Sublime.
> 
> Please comment on this pull request if you experience a problem or if the branch is working here. Thanks.

I'm working on windows. 
was looking for this fix long time mainly cause when i wrap a function the hinting for function parameter wasn't working properly. the new jedi (0.17) release solved that.
so i downloaded the anaconda fix from the link. and worked with it a few days.
the issue with the wrapping is solved! 
also, I've enabled the auto-formatting of the package and this also works nicely. 
I haven't noticed anything weird yet with the package behavior. 

thanks.

**Comment by relikd** [comment]
Wanted to create a new feature request solely for the f-string compatibility. Seems this is already taken care of. When can we expect this to be merged? Would be awesome, thanks for the work 😄

**Comment by DamnWidget** [comment]
Sorry for the delay guys I've been out of the picture for a while just came back recently

**Comment by scuml** [comment]
Great to hear from you again Oscar.  Thanks for the merge.

**Pull request merged**
