### PR TITLE
fix autocomplete not work for python 3.10

### LINKED ISSUE #914: Anaconda autocomplete
Anaconda autocomplete is not working.  I am on Linux and my Sublime Text 3 recently updated.  Prior to the update it worked fine.  I update via the Package Manager.  ST version 4121.  Latest Anaconda version.  I tried uninstalling and reinstalling but it didn't help.

I don't get any errors.  Here is the most recent error in my jsonserver log:
021-11-30 15:23:57,206: ERROR   : Traceback (most recent call last):
  File "/home/malonn/.config/sublime-text/Packages/Anaconda/anaconda_lib/jedi/cache.py", line 109, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/malonn/.config/sublime-text/Packages/Anaconda/anaconda_server/jsonserver.py", line 112, in found_terminator
    self.handle_command(handler_type, method, uid, vid, settings, data)
  File "/home/malonn/.config/sublime-text/Packages/Anaconda/anaconda_server/jsonserver.py", line 140, in handle_command
    handler(method, data, uid, vid, settings, self.return_back, DEBUG_MODE).run()
  File "/home/malonn/.config/sublime-text/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py", line 29, in run
    super(JediHandler, self).run()
  File "/home/malonn/.config/sublime-text/Packages/Anaconda/anaconda_server/lib/anaconda_handler.py", line 49, in run
    command(**kwargs)
  File "/home/malonn/.config/sublime-text/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py", line 99, in doc
    Doc(self.callback, self.uid, self.script, html)
  File "/home/malonn/.config/sublime-text/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py", line 45, in script
    return self.jedi_script(**self.data)
  File "/home/malonn/.config/sublime-text/Packages/Anaconda/anaconda_server/handlers/jedi_handler.py", line 53, in jedi_script
    return jedi.Script(
  File "/home/malonn/.config/sublime-text/Packages/Anaconda/anaconda_lib/jedi/api/__init__.py", line 184, in __init__
    self._inference_state = InferenceState(
  File "/home/malonn/.config/sublime-text/Packages/Anaconda/anaconda_lib/jedi/inference/__init__.py", line 91, in __init__
    self.grammar = environment.get_grammar()
  File "/home/malonn/.config/sublime-text/Packages/Anaconda/anaconda_lib/jedi/cache.py", line 111, in wrapper
    result = method(self, *args, **kwargs)
  File "/home/malonn/.config/sublime-text/Packages/Anaconda/anaconda_lib/jedi/api/environment.py", line 37, in get_grammar
    return parso.load_grammar(version=version_string)
  File "/home/malonn/.config/sublime-text/Packages/Anaconda/anaconda_lib/parso/grammar.py", line 260, in load_grammar
    return load_grammar(**kwargs)
  File "/home/malonn/.config/sublime-text/Packages/Anaconda/anaconda_lib/parso/grammar.py", line 236, in load_grammar
    version_info = parse_version_string(version)
  File "/home/malonn/.config/sublime-text/Packages/Anaconda/anaconda_lib/parso/utils.py", line 176, in parse_version_string
    return _parse_version(version)
  File "/home/malonn/.config/sublime-text/Packages/Anaconda/anaconda_lib/parso/utils.py", line 125, in _parse_version
    raise ValueError('The given version is not in the right format. '
ValueError: The given version is not in the right format. Use something like "3.8" or "3".

I'm running Python 3.10.

### PR DESCRIPTION
**Pull request by DIM-KO**
Fix #914

### CODE REVIEW

**Comment by DamnWidget** [comment]
Do you think a whole Jedi update could be better?

**Comment by DIM-KO** [comment]
Maybe, but it works like that. my skill not high enough

**Comment by MattDMo** [comment]
@DamnWidget this PR simply copies the `grammar39.txt` file contents into a new file `grammar310.txt`.  `grammar39.txt` is a copy of `grammar38.txt`, which comes from [here](https://github.com/python/cpython/blob/3.8/Grammar/Grammar). According to [this page](https://devguide.python.org/grammar/) in the Python Developers Guide, "*Earlier versions* [prior to 3.9] *use a different parser technology.*" I'm guessing the parser that processes these grammar files in Anaconda won't work with the [new grammar files](https://github.com/python/cpython/blob/3.9/Grammar/python.gram) from 3.9 and 3.10 (and beyond), but these versions add new features to the language (the `match`/`case` statements in 3.10 come to mind), which I assume Anaconda users would like to make use of. Does `parso` work with both old and new grammars now?

**Comment by DamnWidget** [comment]
This will be properly fixed in the next release, more info in #921

**Pull request closed without merging**
