### PR TITLE
Underline errors only if anaconda_linter_mark_style is 'none'

### PR DESCRIPTION
**Pull request by muffinmad**

### CODE REVIEW

**Comment by DamnWidget** [comment]
Hi, can you make it configurable?

We already have the `anaconda_linter_underlines` setting so probably is better to check if this is set as `true` in the first part of the conditional or even better just check if this is set as `true` and ignore the mark style alltogether.

**Comment by muffinmad** [comment]
Hi!
It's not a new feature. It's just fixes existing behaviuor.
As for now there are condition on line 194 in anaconda_lib/linting/sublime.py:
`if style != 'none' or style == 'none' and show_underlines:`
and it's always True.

**Comment by muffinmad** [comment]
Oh, i see. I missunderstuded anaconda_linter_underlines description in Anaconda.sublime-settings file.
Can you please explain why hiding underlines while using marks is wrong?

**Comment by DamnWidget** [comment]
I did meant that hiding underlines while using marks is wrong, I meant that don't allow the user to decide when to show underlines is wrong.

**Comment by muffinmad** [comment]
Would it be acceptable to never ignore underline settings then?

**Comment by DamnWidget** [comment]
Yup, that is just what I asked in my first comment :+1:

**Comment by muffinmad** [comment]
My bad. Somehow i not pay attention to second part of your comment.

**Comment by DamnWidget** [comment]
No worries :)

I will merge it on next release

**Pull request merged**
