### PR TITLE
Assignment operator support

### PR DESCRIPTION
**Pull request by scuml**
Python 3.8 introduced assignment operators.  Ex:
```python
if a := get_cache_key("something"):
  print a
```

This was introduced in a recent version of pycodestyle (2.6.0a1) which has been copied into this repo.  A unit test was also created to verify functionality.

### CODE REVIEW

**Comment by DamnWidget** [comment]
Did you check t hat this does not break anything in no operating system?

**Comment by scuml** [comment]
I'm can only verify this works on Mac OS.

**Comment by scuml** [comment]
We have this confirmed working on Windows.  Can a repo watcher try this on Linux and confirm functionality?

**Comment by DamnWidget** [comment]
Seems to be working on Linux

**Pull request merged**
